name: Terraform CI (Azure)

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  terraform:
    runs-on: NewAction

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode azsecret and set env vars (bash only)
        shell: bash
        run: |
          echo "${{ secrets.azsecret }}" > az.json
          export ARM_CLIENT_ID=$(grep -oP '"clientId"\s*:\s*"\K[^"]+' az.json)
          export ARM_CLIENT_SECRET=$(grep -oP '"clientSecret"\s*:\s*"\K[^"]+' az.json)
          export ARM_SUBSCRIPTION_ID=$(grep -oP '"subscriptionId"\s*:\s*"\K[^"]+' az.json)
          export ARM_TENANT_ID=$(grep -oP '"tenantId"\s*:\s*"\K[^"]+' az.json)

          echo "ARM_CLIENT_ID=$ARM_CLIENT_ID" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$ARM_TENANT_ID" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply (main branch only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
